#ifndef AWSIM_DEFAULTS_H
#define AWSIM_DEFAULTS_H

#define AWSIM_DEFAULT_CONSOLE_SOCKET_PATH "/var/run/awsimd"
#define AWSIM_DEFAULT_DYNAMIC_NUMBER_OF_WORKERS true
#define AWSIM_DEFAULT_HTTP_PORT_NUMBER 80
#define AWSIM_DEFAULT_HTTPS_PORT_NUMBER 443
#define AWSIM_DEFAULT_PERCENT_OF_CORES_AS_WORKERS 1.0
#define AWSIM_DEFAULT_ROOT_DIRECTORY "/srv/awsimd/"
#define AWSIM_DEFAULT_STATIC_NUMBER_OF_WORKERS 4

#endif
